# screen/screen update
WIDTH_SCREEN = 600
HEIGHT_SCREEN = 600
SIZE_SCREEN = (WIDTH_SCREEN, HEIGHT_SCREEN)
FPS = 60

# background
COUNT_TILES_BACKGROUND = 3
SPEED_TILES_BACKGROUND = 2

# game
JUMP = 8
GRAVITY = 3
COUNT_PIPES = 3
LEN_PIPES = 530
MIN_POS_TOP_PIPE = - 450  # the sprite is long and therefore overseas
MAX_POS_TOP_PIPE = -50  # the sprite is long and therefore overseas
SPACE = 350
GAP = 90
SPEED_INCREASE_FREQUENCY = 5
RATE_INCREASE_SPEED_PIPE = 0.2
TICKET_DROP_CHANCE = 20  # 1 to 20