# screen/screen update
WIDTH_SCREEN = 600
HEIGHT_SCREEN = 600
SIZE_SCREEN = (WIDTH_SCREEN, HEIGHT_SCREEN)
FPS = 60

# background
COUNT_TILES_BACKGROUND = 3
SPEED_TILES_BACKGROUND = 2

# game
JUMP = 8
GRAVITY = 3
COUNT_PIPES = 6
SPEED_PIPES = 2
LEN_PIPES = 530
MIN_POS_TOP_PIPE = - 450
MAX_POS_TOP_PIPE = -50
# the sprite is long and therefore overseas
SPACE = 300
GAP = 90